services:
    app:
        container_name: app
        build:
            dockerfile: docker/php/Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - db
            - redis
        networks:
            - app-net

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - app-net

    db:
        image: postgres:15-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-laravel}
            POSTGRES_USER: ${DB_USERNAME:-laravel}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-laravel}
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-net

    redis:
        container_name: redis-cache
        image: redis:8-alpine
        networks:
            - app-net

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - app-net

networks:
    app-net:
        driver: bridge
